2022-06-09 23:49:58 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-09 23:49:58 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-09 23:49:58 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-09 23:49:59 WARNING (MainThread) [pydeconz.utils] Received unexpected bridge id: 0000000000000000
2022-06-09 23:49:59 WARNING (MainThread) [pydeconz.utils] Received unexpected bridge id: 0000000000000000
2022-06-11 00:57:04 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-11 00:57:43 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RATE_LIMIT
2022-06-12 01:55:44 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-13 02:55:43 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-13 20:25:44 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [139628077495392] Disconnected: Did not receive auth message within 10 seconds
2022-06-13 20:25:56 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [139628064540848] Disconnected: Did not receive auth message within 10 seconds
2022-06-14 03:55:46 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-14 09:56:30 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [139628174036128] Disconnected: Did not receive auth message within 10 seconds
2022-06-14 13:07:00 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Mi Control Hub' for xiaomi_miio integration not ready yet: DeviceException during setup of xiaomi gateway with host 192.168.1.81; Retrying in background
2022-06-14 20:03:06 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [139628103604256] Disconnected: Did not receive auth message within 10 seconds
2022-06-15 03:23:57 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-15 04:55:47 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-16 03:23:59 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-16 05:55:44 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-17 03:24:00 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-17 06:55:45 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-18 03:24:01 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-18 07:55:45 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-19 03:24:05 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-19 08:55:45 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-20 03:24:06 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-20 09:55:49 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-21 03:24:07 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-21 10:55:48 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-22 03:24:09 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-22 11:55:49 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-23 03:23:59 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-23 12:55:48 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-24 03:23:58 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-24 13:55:48 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-25 03:23:57 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-25 14:55:48 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-26 03:23:59 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-26 15:55:50 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-27 03:24:07 ERROR (MainThread) [homeassistant.components.xiaomi_miio] Timeout fetching Robot vacuum data
2022-06-27 16:55:47 ERROR (MainThread) [custom_components.hacs] <Integration fred-oranje/rituals-genie> GitHub returned 404 for https://api.github.com/repos/fred-oranje/rituals-genie
2022-06-27 22:21:46 ERROR (SyncWorker_4) [homeassistant.util.yaml.loader] while parsing a block mapping
  in "/config/automations.yaml", line 1, column 2
expected <block end>, but found '<block mapping start>'
  in "/config/automations.yaml", line 2, column 3
2022-06-27 22:21:46 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/automations.yaml", line 1, column 2
expected <block end>, but found '<block mapping start>'
  in "/config/automations.yaml", line 2, column 3
2022-06-27 22:21:46 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139628026190528] The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/automations.yaml", line 1, column 2
expected <block end>, but found '<block mapping start>'
  in "/config/automations.yaml", line 2, column 3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 750, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 174, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while parsing a block mapping
  in "/config/automations.yaml", line 1, column 2
expected <block end>, but found '<block mapping start>'
  in "/config/automations.yaml", line 2, column 3
2022-06-27 22:22:24 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot restart because the configuration is not valid: Invalid config for [camera.xiaomi_cloud_map_extractor]: string value is None for dictionary value @ data['host']. Got None. (See ?, line ?). 
2022-06-27 22:22:24 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139628026190528] The system cannot restart because the configuration is not valid: Invalid config for [camera.xiaomi_cloud_map_extractor]: string value is None for dictionary value @ data['host']. Got None. (See ?, line ?). 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 750, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 174, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Invalid config for [camera.xiaomi_cloud_map_extractor]: string value is None for dictionary value @ data['host']. Got None. (See ?, line ?). 
